config/routes.rb
Rails.application.routes.draw do
  root "customers#index"

  resources :customers do
    resources :machines
  end
  resources :employees do
    resources :machines
  end

  #get 'search', to: "customers#search"  
#  resources :machines 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :machines, dependent: :destroy	
	validates :name, presence:  { message: "must be given please" },length: { minimum: 3 }
	validates :email,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create } ,presence:  { message: " must be given please" },length: { minimum: 6 }
	validates :primary_number, presence:  { message: "must be given please" },length: { in: 10..12 }, numericality: { only_integer: true }
	validates :alternate_number, presence:  { message: "must be given please" },length: { in: 10..12 }, numericality: { only_integer: true }
	validates :address, presence:  { message: "must be given please" }, length: {minimum: 10}
	# scope :cust, -> { where(name: "raghu") }
	# scope :cust1, -> { offset(5).limit(10) }
	# scope :cust2, -> { last(5) }
	#........Passing argument in scope ................

	#scope :cust, ->(name) { where("name = ?", name) }
    # condition in scope ......................

    scope :cust, -> { order('id ASC').reorder('name')}
    #Previous working search bar
    #scope :search, -> { where("name LIKE ?","%" +params[:q]+"%") }

  # 	scope :searched, -> (name) {where("name LIKE ?", name)}
		# def searched(name)
  # 		where("name LIKE ?", name)
		# end
########################## Add Search using scope ############## 
	def self.search(search)
		if search
			where(["name LIKE ?","%#{search}%"])
		else
			all
		end
	end
	# scope :created_before, ->(time) { where("created_at < ?", time) if time.present? }
	#default_scope { where(name: false) }

	#################Add Enum in Rails ####################
  enum status: [:open, :closed,:under_review, :pending] 
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :machines, dependent: :destroy

    validates :name, presence: { message: "must be given please" },length: { minimum: 3 }
    validates :mobile_number, presence: { message: "must be given please" },length: { in: 10..12 }, numericality: { only_integer: true }
    validates :pan_card, presence: { message: "must be given please" },length: { in: 3..10 }, numericality: { only_integer: true }
    validates :address, presence:  { message: "must be given please" }, length: {minimum: 10}
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
  enum status: [:active, :inactive], _default: :"active"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.cust
    @customers = Customer.search(params[:search])
  end

  # def search
   
  #   @customers = Customer.search(params[:search])    
  # end

  def show
    @customer = Customer.find(params[:id])
  end
 
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
        render :new
    end

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update 
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end

  end

  def destroy  
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to root_path
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :email, :primary_number, :alternate_number, :address,:status)       
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all 
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render :edit
    end

  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit
    end

  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    redirect_to employees_path
  end

  private
    def employee_params
      params.require(:employee).permit(:name,:mobile_number,:pan_card,:address)
    end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @machine  = @customer.machines.create(machine_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @machine = @customer.machines.find(params[:id])
    @machine.destroy
    redirect_to customer_path(@customer)
    
  end
  
  private
    def machine_params
      params.require(:machine).permit(:name, :model_number, :model_series,:employee_id,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer do |form| %>
  <% if @customer.errors.any? %>
    <h2>Errors</h2>
    <ul>
      <% @customer.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>  
    </ul>
  <% end %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>
  
  <div>
    <%= form.label :primary_number %><br>
    <%= form.text_field :primary_number %>
  </div>

  <div>
    <%= form.label :alternate_number %><br>
    <%= form.text_field  :alternate_number %>

  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :status %><br>
    <%=  form.collection_select :status, Customer.statuses.map{ |a| [a.first,a.first] },  :first, :second %>
  </div>


  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/customers/edit.html.erb
<h1>Test Customer</h1>

<h1>Edit Customer</h1>  
<%= render "form", customer: @customer %>
<%= link_to "Back to Home page Customer",root_path%>

app/views/customers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">
    <div class="row">
      <div class="col-2">
        <a class="navbar-brand" href="/customers">Lotus App</a>
      </div>
        <div class="col-2">
        <a class="navbar-brand" href="/customers">Customer</a>
        </div>
      <div class="col-2">  
      <a class="navbar-brand" href="/employees">Employee</a>
    </div>
<!--     <div class="col-6"  >
      <form class="form-inline my-2 my-lg-0"action="/search">
        <input class="form-control mr-sm-2"name="q"type="text"placeholder="Search" aria-label="Search">
        <button class="btn btn-primary:active my-2 my-sm-0"type="submit">Search</button>
      </form>
    </div> -->


  <%= form_tag customers_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "search" %>
  <% end %>
</div>

  </div>
</nav>
<ul>
	<% @customers.each do |t| %>
		<li>
		  <%= link_to t.name ,t %>
		</li>
	<% end %>
</ul>





<%= link_to "Add New Customer",new_customer_path %>

<br>
<br>

<%= link_to "Add New Employee",new_employee_path %>

app/views/customers/new.html.erb
<h1>Add New Customer</h1>  
<%= render "form", customer: @customer %>
<%= link_to "Back to Home page Customer",root_path%>

app/views/customers/search.html.erb
<br>
<br>

<div>

	<h3 style="color:blue">Search Result</h3>  

    	<% @customers.each do |result| %>
    	    
    	    <p style="color:red"></p>  
        	<%= result.name %><br>
 
        	<%= result.email %><br>
  
        	<%= result.primary_number %><br>
        	<%= result.alternate_number %><br>
        	<%= result.address %><br>
    	<% end %>
</div>

<div class="alert alert-success">
  <strong>Success!</strong> This is  your search result.
</div>

<ul>
	<li><%= link_to "Back To Home Page", root_path %></li>
</ul>

app/views/customers/show.html.erb
<h1><%= @customer.name  %></h1>

<p><%= @customer.email  %></p>

<p><%= @customer.primary_number  %></p>

<p><%= @customer.alternate_number  %></p>

<p><%= @customer.address  %></p>

<p><%= @customer.status  %></p>
	
<ul>
  <li><%= link_to "Edit", edit_customer_path(@customer) %></li>

  <li><%= link_to 'Destroy', customer_path(@customer),
                  method: :delete,
                  data: { confirm: "Are you sure You want to delete This Customer ?" } %></li>  

  <li><%= link_to "Back", customers_path %></li>
</ul>

<h2>Machines</h2>
<%= render @customer.machines %>
<div>
  <h2>Add a Machine:</h2>
</div>
<%= render 'machines/form' %>
<!%= render 'machines/form1' %>

app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
  <% if @employee.errors.any? %>
    <h2>Errors</h2>
    <ul>
      <% @employee.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>  
    </ul>
  <% end %>
  <div>
    <p style="text-align:center;">  
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <p style="text-align:center;"> 
    <%= form.label :mobile_number %><br>
    <%= form.text_field :mobile_number %>
  </div>

  <div>
    <p style="text-align:center;"> 
    <%= form.label :pan_card %><br>
    <%= form.text_field :pan_card %>

  </div>
  
  <div>
    <p style="text-align:center;"> 
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>
  </p>
  <div>
    <p style="text-align:center;"> 
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>  
<%= render "form", employee: @employee %>
<%= link_to "Back to Home page Employee",employees_path%>

app/views/employees/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
  	<div class="row">
  		<div class="col-5">
          <a class="navbar-brand" href="/employees">Employee</a>
        </div>
        <div class="col-6">
      		<a class="navbar-brand" href="/customers">Customer</a>
        </div>
    </div>	
  </div>
 
</nav>
<ul>
	<% @employees.each do |t| %>
		<li>
		  <%= link_to t.name ,t %>
		</li>
	<% end %>
</ul>

<%= link_to "Add New Employee",new_employee_path %>
<br>
<br>
<%= link_to "Back to Lotus Application Home page ",root_path%>

app/views/employees/new.html.erb
<h1>Add New Employee</h1>  
<%= render "form", employee: @employee %>
<%= link_to "Back to Home page Employee",employees_path%>

app/views/employees/show.html.erb
<h1><%= @employee.name  %></h1>

<p><%= @employee.mobile_number  %></p>

<p><%= @employee.pan_card  %></p>


<p><%= @employee.address  %></p>
	
<ul>
  <li><%= link_to "Edit", edit_employee_path(@employee) %></li>

  
  <li><%= link_to "Delete Employee", employee_path(@employee),
                  method: :delete,
                  data: { confirm: "Are you sure You want to delete This Employee ?" } %></li>   
                                    
  <li><%= link_to "Back", employees_path %></li>
                  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotusApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/_form.html.erb
<%= form_with model: [ @customer, @customer.machines.build ] do |form| %>


  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :model_number %><br>
    <%= form.text_field :model_number %>
  </div>  
  
  <div>
    <%= form.label :model_series %><br>
    <%= form.text_field :model_series %>
  </div>   

  <p>
   
    <%= form.label :name %><br>
    <%= form.select("employee_id", Employee.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %>
  </p>  


  <div class="field">
    <%= form.label :status %><br>
    <%=  form.collection_select :status, Machine.statuses.map{ |a| [a.first,a.first] },  :first, :second %>
  </div>
<br>
  <p>
   
    <%= form.submit%>
  </p>
<% end %>

app/views/machines/_machine.html.erb
<p>
  <strong>Name:</strong>
  <%= machine.name %>
</p>

<p>
  <strong>Model_number:</strong>
  <%= machine.model_number %>
</p>

<p>
  <strong>Model_series:</strong>
  <%= machine.model_series %>
</p>

<p>
  <strong>Employee_id:</strong>
  <%= machine.employee_id %>
</p>

<p>
  <strong>Employee_name:</strong>
  <%= machine.employee.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= machine.status  %>
</p>

<p>
  <%= link_to 'Delete Machine', [machine.customer, machine],
              method: :delete,
              data: { confirm: "Are you sure You want to delete this machine?" } %>
</p>